const videosshort = [
  { title: "He looks like an inner peace that contradicts reality 😭", url: "https://cdn.videy.co/pJUHLkt51.mp4" },
  { title: "Nutted a simple caption 😉", url: "https://cdn.videy.co/EGFcCPEp1.mp4" },
  { title: "Oh She's Having Her Way", url: "https://cdn.videy.co/7uJnxSnX1.mp4" },
  { title: "what we do at girls night", url: "https://cdn.videy.co/krDRMmFI1.mp4" },
  { title: "Hang in there even it’s hard to stay grounded", url: "https://cdn.videy.co/HVikn9a81.mp4" },
  { title: "Nahh this beautiful gonna put you to sleep", url: "https://cdn.videy.co/y6E3IGEY1.mp4" },
  { title: "Pure Cinema", url: "https://cdn.videy.co/NaUNxzDd1.mp4" },
  { title: "Nigga started giggling like a lil girl😂", url: "https://cdn.videy.co/8uUC37DP1.mp4" },
  { title: "True friends help each other", url: "https://cdn.videy.co/dRScbvL91.mp4" },
  { title: "What Happens at The After Hour Kickback", url: "https://cdn.videy.co/t4DgE8X31.mp4" },
  { title: "You did that with a straight face?", url: "https://qu.ax/JqpGC.mp4" },
  { title: "Feeling hot and stuffy need a refresher", url: "https://cdn.videy.co/wYi48TVx1.mp4" },
  { title: "Campus Was Quiet, But Not Our Room...", url: "https://qu.ax/WcKGj.mp4" },
  { title: "Blue haired white girl getting plowed 🫣🤫", url: "https://cdn.videy.co/NohhKoHG1.mp4" },
  { title: "This hair so soft 😍", url: "https://cdn.videy.co/902qMCED1.mp4" },
  { title: "I need a quick vacay 😩🍆", url: "https://cdn.videy.co/hlijS7M41.mp4" },
  { title: "Heavy duty smashed a nut for milk 🍯", url: "https://cdn.videy.co/meYaxZ721.mp4" },
  { title: "vomited after doing it..", url: "https://cdn.videy.co/fm9CTevk1.mp4" },
  { title: "Nutted before it even broken 🥜", url: "https://cdn.videy.co/xf8oJJVF1.mp4" },
  { title: "twins but both like each other", url: "https://cdn.videy.co/nR06BwLN1.mp4" },
  { title: "Outside be givin’ energy y’all ain’t ready for", url: "https://cdn.videy.co/xQrsVFUG1.mp4" },
  { title: "so happy in front of the cams. shawty didn't care at all", url: "https://cdn.videy.co/PpwarT1i1.mp4" },
  { title: "Back aisle energy hittin different, who ridin’ wit me tho? 😏", url: "https://cdn.videy.co/ypGcX02K1.mp4" },
  { title: "I know he be having a time 🤭💫", url: "https://cdn.videy.co/dnh0f2RE1.mp4" },
  { title: "Why it movin like it got beef wit gravity??", url: "https://cdn.videy.co/qa8cpVUt1.mp4" },
  { title: "Drip so loud, even the lollipop jealous", url: "https://cdn.videy.co/HNBrBlPb1.mp4" },
  { title: "jenise had the whole field on lock 😌🙄", url: "https://cdn.videy.co/diIs7T4m1.mp4" },
  { title: "She movin’ like rent due tomorrow frfr 💃🏽✨", url: "https://cdn.videy.co/qLvxKUsP1.mp4" },
  { title: "Ice Cream machine was down", url: "https://cdn.videy.co/kRymrbEy1.mp4" },
  { title: "That’s a lot, can y’all guess what it is?", url: "https://cdn.videy.co/vIJtUbZb1.mp4" },
  { title: "She said ‘trust me’… now I’m halfway to Narnia 💀🪜", url: "https://cdn.videy.co/8Mv9s5fz1.mp4" },
  { title: "Y’all know scrubs don’t always mean healthcare", url: "https://cdn.videy.co/hZVXkhEN1.mp4" },
  { title: "this magic trick works", url: "https://cdn.videy.co/jI9Npkgl1.mp4" },
  { title: "Walmart Employee on Break😮‍💨", url: "https://cdn.videy.co/H2JOevbT1.mp4" },
  { title: "back blown, mark show😮‍💨", url: "https://cdn.videy.co/c49m0jv41.mp4" },
  { title: "enough to make you weak!", url: "https://cdn.videy.co/lTQwNMZ01.mp4" },
  { title: "Whole vibe got ruined when moms kicked in 😩💀", url: "https://cdn.videy.co/MnKgKKyj1.mp4" },
  { title: "Phone buzzin’ like it owe me somethin’", url: "https://cdn.videy.co/9GpM672v1.mp4" },
  { title: "Whole aisle turned into a runway—she walked like she meant it", url: "https://cdn.videy.co/PCpGA1Vi1.mp4" },
  { title: "This the kinda pretty that make traffic stop", url: "https://cdn.videy.co/edhWodl51.mp4" },
  { title: "this one’s got me like ‘wait, WHAT?", url: "https://cdn.videy.co/pjwmPwyC1.mp4" },
  { title: "I'm thirsty and hungry😋😌", url: "https://cdn.videy.co/P4XsMvTt1.mp4" }
];
