window.videosLong = [
  { title: "Auntie sleepin like she the dream I been tryna catch", url: "https://cdn.videy.co/eXR3LYr91.mp4" },
  { title: "Just me, the couch, and a storm of thoughts", url: "https://cdn.videy.co/UaWk9f371.mp4" },
  { title: "Y’all want coffee or compliments? Cuz I’m servin both", url: "https://cdn.videy.co/oHlRqQXt1.mp4" },
  { title: "Can anyone come help her?🫤🙄", url: "https://cdn.videy.co/Uy5OoDJU1.mp4" },
  { title: "\"Even your dreams didn't see this coming!\"", url: "https://cdn.videy.co/cflkrsX91.mp4" },
  { title: "Catching You Up on What Happened Last Night", url: "https://qu.ax/GUrQF.mp4" },
  { title: "Real Love Never Fades, It Lives in Our Memories", url: "https://qu.ax/lHVZX.mp4" },
  { title: "Little freshness, big difference", url: "https://qu.ax/bPkFX.mp4" },
  { title: "Collecting Little Moments of Happiness", url: "https://qu.ax/lZoJr.mp4" },
  { title: "Ageless wonder… Melting my thoughts away.", url: "https://cdn.videy.co/Y39ZyMV71.mp4" },
  { title: "She really said: “You thought this was still PG?”", url: "https://cdn.videy.co/bacYouZf1.mp4" },
  { title: "Stronger Every Day, No Matter the Age", url: "https://qu.ax/SruTG.mp4" },
  { title: "This surpasses every expectation you've ever held", url: "https://cdn.videy.co/Fr9UXpzI1.mp4" },
  { title: "Just a Casual Day, Until My Bestie Showed Up!", url: "https://qu.ax/xUUJA.mp4" },
  { title: "Just Us, Just Relaxing 😍", url: "https://qu.ax/wFKqP.mp4" },
  { title: "As calm and bright as the endless blue sky.", url: "https://qu.ax/hoden.mp4" },
  { title: "Wait… Is This Really You", url: "https://cdn.videy.co/ZrUH2kQN1.mp4" },
  { title: "One Day, the Right Heart Will Find Mine", url: "https://qu.ax/vSzLF.mp4" },
  { title: "At first he was embarrassed but then he enjoyed it.", url: "https://cdn.videy.co/j1jYpR671.mp4" },
  { title: "I’m stunned. Shocked. Shooketh", url: "https://cdn.videy.co/6s1kulFN1.mp4" },
  { title: "This is why I can’t focus in class someone’s daughter be looking like this", url: "https://cdn.videy.co/q6B6YU5m1.mp4" },
  { title: "The Lady in Red Couldn’t Resist 🔥", url: "https://cdn.videy.co/e1BnGwaI1.mp4" },
  { title: "Alone but never bored 🔥", url: "https://cdn.videy.co/rfaSO2VX1.mp4" },
  { title: "This presentation already stole my full attention ❤️", url: "https://qu.ax/lFJxz.mp4" },
  { title: "She makes every moment brighter!", url: "https://cdn.videy.co/5OfusNis1.mp4" },
  { title: "Comment it u like", url: "https://cdn.videy.co/H04aRQXb1.mp4" },
  { title: "u starting early 😋", url: "https://cdn.videy.co/mxfIlurk1.mp4" },
  { title: "Nutted before it even got in", url: "https://cdn.videy.co/BbHcXuJo1.mp4" },
  { title: "Have to try she has.. Chocolate", url: "https://cdn.videy.co/luhOHPc61.mp4" },
  { title: "Even your dreams didn't see this coming!...", url: "https://qu.ax/Haluh.mp4" },
  { title: "she had receipts,but the streets got footage 👀🎥", url: "https://cdn.videy.co/CNJiyMKc1.mp4" },
  { title: "Man’s movin like he got secrets in that box 📦😳", url: "https://cdn.videy.co/v8MytFTU1.mp4" },
  { title: "Backseat Banter Level: Legendary😒", url: "https://cdn.videy.co/APtcpzv71.mp4" },
  { title: "Whole car feel like a reality show rn 🤦🏾‍♂️😂", url: "https://cdn.videy.co/Tvs4eQPF1.mp4" },
  { title: "I’m tryna get sentenced to life 😩💯👮🏾‍♀️", url: "https://cdn.videy.co/wd9Lolh81.mp4" },
  { title: "She got that ‘come clean this mess’ energy 😏🧹", url: "https://cdn.videy.co/09nCL1o11.mp4" },
  { title: "the type of hg I need", url: "https://cdn.videy.co/Dpo1ZotY1.mp4" },
  { title: "Tag someone who’s sweeter than Godiva", url: "https://cdn.videy.co/Wk6eLMXr1.mp4" },
  { title: "Head lecturer", url: "https://cdn.videy.co/w2U9aQVq1.mp4" },
  { title: "When the vibes hit record mode", url: "https://cdn.videy.co/02NElcy71.mp4" }
];
