const videos_popular = [
  { title: "She does it again", url: "https://cdn.videy.co/Vdghj3qe1.mp4" },
  { title: "1st day at work", url: "https://cdn.videy.co/9RRDFBCg1.mp4" },
  { title: "Wake wakey", url: "https://cdn.videy.co/HQ2HFg1n1.mp4" },
  { title: "A natural dog", url: "https://cdn.videy.co/2rVtS1zX1.mp4" },
  { title: "Can I be a good model?", url: "https://cdn.videy.co/X01bycJc1.mp4" },
  { title: "Ngwana tired", url: "https://cdn.videy.co/X0wb4TG31.mp4" },
  { title: "New iPhone Bought it", url: "https://cdn.videy.co/ccjlsQuF1.mp4" },
  { title: "Visiting my sister inlaw", url: "https://cdn.videy.co/ccJKONKg1.mp4" },
  { title: "Morning 🌄", url: "https://cdn.videy.co/JmqrrOnf1.mp4" },
  { title: "BOTAK VIRAL", url: "https://cdn.videy.co/7m9yIP491.mp4" },
  { title: "ANACONDA", url: "https://cdn.videy.co/iwZYVTLx1.mp4" },
  { title: "She is very demure", url: "https://cdn.videy.co/Szmectu51.mp4" },
  { title: "in the moge", url: "https://cdn.videy.co/V5YICRMn1.mp4" },
  { title: "she handle this", url: "https://cdn.videy.co/08LM4jgT1.mp4" },
  { title: "she cant handle this", url: "https://cdn.videy.co/OiqNWB3t1.mp4" },
  { title: "car party", url: "https://cdn.videy.co/OiVYJHts1.mp4" },
  { title: "free and young", url: "https://cdn.videy.co/0fpvpxNb1.mp4" },
  { title: "barber girls", url: "https://cdn.videy.co/DNTngSOr1.mp4" },
  { title: "JOKER", url: "https://cdn.videy.co/lSCTcvCi1.mp4" },
  { title: "Can you handle all this", url: "https://cdn.videy.co/9xOHstVq1.mp4" },
  { title: "Which sneakers must I wear?", url: "https://cdn.videy.co/j9X4fTiE1.mp4" },
  { title: "how hard you work", url: "https://cdn.videy.co/a1K3moKR1.mp4" },
  { title: "dating for free on", url: "https://cdn.slicedrive.com/HidkeCPH1.mp4" },
  { title: "look fabulous", url: "https://cdn.videy.co/DfC9YjqS1.mp4" },
  { title: "I’m a handful", url: "https://cdn.videy.co/KWkw0QJp1.mp4" },
  { title: "it’s not often lol", url: "https://cdn.videy.co/0e7ygBPY1.mp4" },
  { title: "she cool?", url: "https://cdn.videy.co/KdqJQMmO1.mp4" },
  { title: "OVER SIZE", url: "https://cdn.videy.co/rRpGldSD1.mp4" },
  { title: "The type you don’t find twice", url: "https://cdn.videy.co/TQdjgWtQ1.mp4" },
  { title: "Yummy", url: "https://cdn.videy.co/RjMZi9AC1.mp4" },
  { title: "I CANT EAT IT", url: "https://cdn.videy.co/NHHrQ3Kp1.mp4" },
  { title: "APT APT", url: "https://cdn.videy.co/Jbi7MAeZ1.mp4" },
  { title: "wc APT", url: "https://cdn.videy.co/UcsKJqHY1.mp4" },
  { title: "PARTY TIME", url: "https://cdn.videy.co/twIzrMdU1.mp4" },
  { title: "BALON PARTY", url: "https://cdn.videy.co/8nvy62J51.mp4" },
  { title: "daylight", url: "https://cdn.videy.co/jVcfraSq1.mp4" },
  { title: "Moorish Woman", url: "https://cdn.videy.co/7xJ9z05p1.mp4" },
  { title: "big fine mamacita", url: "https://cdn.videy.co/rWbC0Th91.mp4" },
  { title: "BLACK MAMBA", url: "https://cdn.videy.co/jC74bg5E1.mp4" },
  { title: "STUCK IN DAY", url: "https://cdn.videy.co/mfAWhrhs1.mp4" },
  { title: "AFTER PARTY", url: "https://cdn.videy.co/rWXqeML81.mp4" },
  { title: "GREEN GRASS", url: "https://cdn.videy.co/4EzQXzHl1.mp4" },
  { title: "LEOPARD", url: "https://cdn.videy.co/UlyJXvQZ.mp4" },
  { title: "wowsers", url: "https://cdn.videy.co/aGhe2eyJ1.mp4" },
  { title: "SMILE HAPPY", url: "https://cdn.videy.co/7SuIGYFZ1.mp4" },
  { title: "CANT YOU FEEL", url: "https://cdn.videy.co/3gOFBHSb.mp4" },
  { title: "ICE CREAM FREE", url: "https://cdn.videy.co/KE7tYOLE1.mp4" },
  { title: "ARE YOU SURE?", url: "https://cdn.videy.co/d9jAHPPl1.mp4" },
  { title: "chocolate delicious", url: "https://cdn.videy.co/3rq1gjlG1.mp4" },
  { title: "ARRIVE AT THE APT", url: "https://cdn.videy.co/vXrYKPpj1.mp4" },
  { title: "Not me tryna work n life said ‘BOOM!’ 😩", url: "https://cdn.videy.co/4ehUx7Ho1.mp4" },
  { title: "Feelin’ cute, might bless y’all timeline later", url: "https://cdn.videy.co/Y8ddXfmg1.mp4" },
  { title: "Bro actin’ like he broke da 8-ball curse 😂", url: "https://cdn.videy.co/nfyWokYV1.mp4" },
  { title: "Big Mama🤭", url: "https://cdn.videy.co/UiatIFtr1.mp4" },
  { title: "Me as soon as I feel a lil breeze🥰", url: "https://cdn.videy.co/KGJpNqq11.mp4" },
  { title: "“What’s your type”", url: "https://cdn.videy.co/ycVRkrG91.mp4" },
  { title: "This Is What Happens When You Lose Control.😀😀", url: "https://cdn.videy.co/kYhaztYp1.mp4" },
  { title: "yall apartments!!😭", url: "https://cdn.videy.co/kM5IRZaQ1.mp4" },
  { title: "Best Friends in the World", url: "https://cdn.videy.co/KR6pnsfX1.mp4" },
  { title: "Last party", url: "https://cdn.videy.co/s9hIEukB1.mp4" }
];
